// <auto-generated />
using Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260220023031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Flight.Models.FlightList", b =>
                {
                    b.Property<int>("FlightListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightListId");

                    b.ToTable("FlightList");

                    b.HasData(
                        new
                        {
                            FlightListId = 1,
                            Date = "2026-03-10",
                            FlightNumber = "AA101",
                            From = "New York",
                            Price = 350,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightListId = 2,
                            Date = "2026-03-12",
                            FlightNumber = "DL202",
                            From = "Dallas",
                            Price = 420,
                            To = "Los Angeles"
                        },
                        new
                        {
                            FlightListId = 3,
                            Date = "2026-03-15",
                            FlightNumber = "UA303",
                            From = "Houston",
                            Price = 280,
                            To = "Miami"
                        },
                        new
                        {
                            FlightListId = 4,
                            Date = "2026-03-18",
                            FlightNumber = "SW404",
                            From = "Chicago",
                            Price = 300,
                            To = "New York"
                        },
                        new
                        {
                            FlightListId = 5,
                            Date = "2026-03-20",
                            FlightNumber = "JB505",
                            From = "Los Angeles",
                            Price = 390,
                            To = "Dallas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
